[program:meilisearch]
command=/usr/bin/meilisearch --http-addr 127.0.0.1:7700 --env development --db-path /data/meilisearch
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=50
